Create modal
js-tasks-ru/htmlcss-20230411_julia-kurianova pull request #12
Opened 2023-04-30 19:45 UTC by judy99

2023-04-30 19:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-01 12:26 UTC, GSemikozov requested changes

2023-05-01 12:26 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +        <div class="modal">
id - здесь

2023-05-01 12:26 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: relative;
позиционируем весь блок через fixed

2023-05-01 12:26 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: relative;
и растягиваем на всю ширину и высоту

2023-05-01 12:26 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__wrapper {
и тогда этот элемент будет лишним

2023-05-01 21:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-01 22:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-01 22:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-02 16:52 UTC, GSemikozov approved these changes

2023-05-02 16:52 UTC, merged