Implement mobile design for a main page
js-tasks-ru/htmlcss-20230411_julia-kurianova pull request #13
Opened 2023-05-02 14:54 UTC by judy99

2023-05-02 14:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-02 15:03 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-03 01:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-03 14:34 UTC, GSemikozov requested changes

2023-05-03 14:34 UTC, GSemikozov commented on components/header/header.css
> +    width: 80%;
лишнее ограничение, контент складываем в container

2023-05-03 14:34 UTC, GSemikozov commented on components/footer/footer.css
> +        padding: 0 10px 136px;
паддинг снизу - свойство блока

2023-05-03 14:34 UTC, GSemikozov commented on components/component/component.css
> +    padding: 32px 0 62px 42px;
а такие отступы у тайтла точно нужны?)

проще на уровне блока общие отступы раскидать.

2023-05-07 19:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-07 19:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-12 13:33 UTC, GSemikozov commented on components/component/component.css
> +.component__tabs {
табы как отдельный компонент будем делать попозже, я рекомендую пока убрать этот код (можно сохранить где-то)

2023-05-16 08:05 UTC, merged