Lesson 05: tabs for main page
js-tasks-ru/htmlcss-20230411_julia-kurianova pull request #25
Opened 2023-06-03 00:44 UTC by judy99

2023-06-03 00:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-03 10:16 UTC, GSemikozov requested changes

2023-06-03 10:16 UTC, GSemikozov commented on components/tabs/tabs.css
> +#all-tab:checked ~ .tabs__content_complex,
не стоит обрабатывать везде кейс, когда один таб включен, то остальные - выключаем; они и там будут по умолчанию выключены, посколько type="radio" включает только одну активную опцию)

2023-06-03 10:16 UTC, GSemikozov commented on components/tabs/tabs.css
> +#all-tab:checked ~ .tabs__content_complex,
ну и лучше и здесь id заменить на классы (а вдруг на странице у нас будет 2 компонента табов?)

2023-06-03 10:16 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__button {
эта кнопка не нужна, удалим

2023-06-05 18:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-07 21:17 UTC, GSemikozov approved these changes

2023-06-07 21:17 UTC, merged